// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMNI1CTFmAAGyBpvllSHBezzrYkCLmC_E',
    appId: '1:86057455454:web:7cffe492b654beb364c9cf',
    messagingSenderId: '86057455454',
    projectId: 'relics-data',
    authDomain: 'relics-data.firebaseapp.com',
    storageBucket: 'relics-data.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB350N1NuYYccJbOIr88XCOS7G3cntDX9E',
    appId: '1:86057455454:android:b725b9876fc00a9864c9cf',
    messagingSenderId: '86057455454',
    projectId: 'relics-data',
    storageBucket: 'relics-data.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhNfooBm-GdyOQMq0NgCusZF-Fvppd1P8',
    appId: '1:86057455454:ios:ab33c98d8d9b9f0964c9cf',
    messagingSenderId: '86057455454',
    projectId: 'relics-data',
    storageBucket: 'relics-data.appspot.com',
    iosBundleId: 'com.example.relics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhNfooBm-GdyOQMq0NgCusZF-Fvppd1P8',
    appId: '1:86057455454:ios:19b817184b2dfc0c64c9cf',
    messagingSenderId: '86057455454',
    projectId: 'relics-data',
    storageBucket: 'relics-data.appspot.com',
    iosBundleId: 'com.example.relics.RunnerTests',
  );
}
